### ISSUE TITLE
Config is being served with the front end

### ISSUE THREAD

**Issue by KyrumX** [anti-social-engineers/Ace-Card-Front-end#1]
Config moet niet in de source (element inspect) of github aanwezig zijn.
Dus exclude + .gitignore.

**Comment by KyrumX** [comment]
https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables
https://stackoverflow.com/questions/30568796/how-to-store-configuration-file-and-read-it-using-react
https://stackoverflow.com/questions/48699820/how-do-i-hide-api-key-in-create-react-app

**Comment by MelleNout** [comment]
Fixed
