### ISSUE TITLE
Empty page when refresh

### ISSUE THREAD

**Issue by KyrumX** [anti-social-engineers/Ace-Card-Front-end#14]

**Comment by KyrumX** [comment]
Na inloggen direct naar account is lege pagina

**Comment by KyrumX** [comment]
Users die een kaart hebben kunnen niet naar /Dashboard

**Comment by KyrumX** [comment]
+Confirmed on development branch. API works, its front end related.

**Comment by SelimAydi** [comment]
Weird, Lisse heeft een kaart en die heeft wel direct toegang. Bedoel je users die geen kaart hebben missch
